#!/bin/bash

# requires "pv" first i.e. sudo apt-get install pv 


echo -ne ' ▓▓                          [10%]\r'
sleep 0.2
echo -ne ' ▓▓▓▓                        [20%]\r'
sleep 0.2
echo -ne ' ▓▓▓▓▓▓                      [30%]\r'
sleep 0.2
echo -ne ' ▓▓▓▓▓▓▓▓                    [40%]\r'
sleep 0.2
echo -ne ' ▓▓▓▓▓▓▓▓▓▓                  [50%]\r'
sleep 0.2
echo -ne ' ▓▓▓▓▓▓▓▓▓▓▓▓                [60%]\r'
sleep 0.2
echo -ne ' ▓▓▓▓▓▓▓▓▓▓▓▓▓▓              [70%]\r'
sleep 0.2
echo -ne ' ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓            [80%]\r'
sleep 0.2
echo -ne ' ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓          [90%]\r'
sleep 0.2
echo -ne ' ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓        [100%]\r'
sleep 0.2
echo " ////////[ _L0G1N _C0MPL3TE ]" | pv -qL 45
